import avatar from "../../public/assets/avatar.jpg";
import avatar2 from "../../public/assets/avatar2.jpg";
import avatar3 from "../../public/assets/avatar3.png";
import avatar4 from "../../public/assets/avatar4.jpg";
const getRandomDepartment = () => {
  const departments = ["IT", "HR", "Marketing", "Finance", "Operations"];
  return departments[Math.floor(Math.random() * departments.length)];
};

const getRandomContractStatus = () => {
  const contractStatuses = ["Expired", "Ongoing", "Long-term", "Ended"];
  return contractStatuses[Math.floor(Math.random() * contractStatuses.length)];
};
const getRandomStatusBackground = () => {
  const list = ["#FB9678", "#FF5C8E", "#03C9D7", "#8BE78B"];
  return list[Math.floor(Math.random() * list.length)];
};

export const employeesData = [
  {
    employeeId: 1,
    name: "Phan Hien",
    position: "Project Manager",
    image: avatar,
    reportTo: "Minh Tri",
    contractStatus: getRandomContractStatus(),
    salary: "2000$",
    hireDate: "01/02/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 2,
    name: "John Doe",
    position: "Software Engineer",
    image: avatar2,
    reportTo: "Phan Hien",
    contractStatus: getRandomContractStatus(),
    salary: "1800$",
    hireDate: "15/03/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 3,
    name: "Jane Smith",
    position: "UX/UI Designer",
    image: avatar3,
    reportTo: "Minh Tri",
    contractStatus: getRandomContractStatus(),
    salary: "2200$",
    hireDate: "10/04/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 4,
    name: "Alice Johnson",
    position: "Marketing Specialist",
    image: avatar4,
    reportTo: "Phan Hien",
    contractStatus: getRandomContractStatus(),
    salary: "1900$",
    hireDate: "05/05/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 5,
    name: "Michael Brown",
    position: "Financial Analyst",
    image: avatar,
    reportTo: "Minh Tri",
    contractStatus: getRandomContractStatus(),
    salary: "2100$",
    hireDate: "20/06/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 6,
    name: "Sarah Lee",
    position: "HR Manager",
    image: avatar2,
    reportTo: "Minh Tri",
    contractStatus: getRandomContractStatus(),
    salary: "2300$",
    hireDate: "12/07/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 7,
    name: "David Wilson",
    position: "Sales Executive",
    image: avatar3,
    reportTo: "Phan Hien",
    contractStatus: getRandomContractStatus(),
    salary: "1950$",
    hireDate: "18/08/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 8,
    name: "Emily Garcia",
    position: "Graphic Designer",
    image: avatar4,
    reportTo: "Jane Smith",
    contractStatus: getRandomContractStatus(),
    salary: "1800$",
    hireDate: "25/09/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 9,
    name: "Daniel Clark",
    position: "Product Manager",
    image: avatar,
    reportTo: "Phan Hien",
    contractStatus: getRandomContractStatus(),
    salary: "2200$",
    hireDate: "30/10/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 10,
    name: "Olivia Martinez",
    position: "Content Writer",
    image: avatar2,
    reportTo: "Sarah Lee",
    contractStatus: getRandomContractStatus(),
    salary: "1700$",
    hireDate: "02/11/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 11,
    name: "William Anderson",
    position: "IT Support Specialist",
    image: avatar3,
    reportTo: "Minh Tri",
    contractStatus: getRandomContractStatus(),
    salary: "1900$",
    hireDate: "08/12/2021",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 12,
    name: "Ava Thomas",
    position: "Business Analyst",
    image: avatar4,
    reportTo: "Daniel Clark",
    contractStatus: getRandomContractStatus(),
    salary: "2100$",
    hireDate: "14/01/2022",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 13,
    name: "Ethan Hernandez",
    position: "Quality Assurance Analyst",
    image: avatar,
    reportTo: "John Doe",
    contractStatus: getRandomContractStatus(),
    salary: "1750$",
    hireDate: "20/02/2022",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 14,
    name: "Mia Lopez",
    position: "Customer Support Specialist",
    image: avatar2,
    reportTo: "David Wilson",
    contractStatus: getRandomContractStatus(),
    salary: "1850$",
    hireDate: "25/03/2022",
    department: getRandomDepartment(),
    StatusBg: getRandomStatusBackground(),
  },
  {
    employeeId: 15,
    name: "Noah Perez",
    position: "Data Analyst",
    image: avatar3,
    reportTo: "Jane Smith",
    contractStatus: getRandomContractStatus(),
    salary: "2000$",
    hireDate: "01/04/2022",
    department: getRandomDepartment(),
  },
];
